version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      day: 'tuesday'
      interval: 'monthly'
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      day: 'tuesday'
      interval: 'monthly'
    pull-request-branch-name:
      separator: '-'
    open-pull-requests-limit: 99
    target-branch: 'main'
    commit-message:
      prefix: 'chore'
      include: 'scope'
