services:
  - type: worker
    runtime: node
    name: xmtp-agent-sdk-starter
    repo: https://github.com/xmtp/agent-sdk-starter
    numInstances: 1
    region: frankfurt
    plan: starter
    branch: main
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: XMTP_WALLET_KEY
        sync: false
      - key: XMTP_DB_ENCRYPTION_KEY
        sync: false
      - key: XMTP_DB_DIRECTORY
        value: '/var/data'
      - key: XMTP_ENV
        value: 'production'
      - key: XMTP_FORCE_DEBUG_LEVEL
        value: 'error'
      - key: XMTP_FORCE_DEBUG
        value: 'true'
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
